<?php

namespace Database\Seeders;

use App\Models\Tool;
use App\Models\User;
use Illuminate\Database\Seeder;

class ToolSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::where('role', 'admin')->first();

        $tools = [
            [
                'user_id' => $admin->id,
                'name' => 'JSON Formatter & Validator',
                'slug' => 'json-formatter',
                'description' => 'Format, validate, and beautify JSON data with syntax highlighting and error detection. Perfect for API testing and debugging.',
                'icon' => 'json',
                'category' => 'JSON',
                'url' => '/tools/json-formatter',
                'documentation_url' => 'https://www.json.org/json-en.html',
                'is_active' => true,
                'is_featured' => true,
                'usage_count' => 15420,
                'created_at' => now()->subMonths(6),
                'updated_at' => now(),
            ],
            [
                'user_id' => $admin->id,
                'name' => 'API Request Viewer',
                'slug' => 'api-viewer',
                'description' => 'Inspect, analyze, and debug API requests and responses. View headers, payloads, and response times in a beautiful interface.',
                'icon' => 'api',
                'category' => 'API',
                'url' => '/tools/api-viewer',
                'documentation_url' => 'https://developer.mozilla.org/en-US/docs/Web/HTTP',
                'is_active' => true,
                'is_featured' => true,
                'usage_count' => 8932,
                'created_at' => now()->subMonths(5),
                'updated_at' => now(),
            ],
            [
                'user_id' => $admin->id,
                'name' => 'URL Slug Generator',
                'slug' => 'slug-generator',
                'description' => 'Generate SEO-friendly URL slugs from any text. Supports multiple languages and special character handling.',
                'icon' => 'slug',
                'category' => 'Text',
                'url' => '/tools/slug-generator',
                'documentation_url' => null,
                'is_active' => true,
                'is_featured' => false,
                'usage_count' => 21567,
                'created_at' => now()->subMonths(8),
                'updated_at' => now(),
            ],
            [
                'user_id' => $admin->id,
                'name' => 'Markdown Preview',
                'slug' => 'markdown-preview',
                'description' => 'Write and preview Markdown in real-time. Includes syntax highlighting for code blocks and table support.',
                'icon' => 'markdown',
                'category' => 'Markdown',
                'url' => '/tools/markdown-preview',
                'documentation_url' => 'https://www.markdownguide.org/',
                'is_active' => true,
                'is_featured' => true,
                'usage_count' => 12453,
                'created_at' => now()->subMonths(4),
                'updated_at' => now(),
            ],
            [
                'user_id' => $admin->id,
                'name' => 'Text Utilities',
                'slug' => 'text-utilities',
                'description' => 'Collection of text manipulation tools: case converter, character counter, word counter, line sorter, and text cleaner.',
                'icon' => 'text',
                'category' => 'Text',
                'url' => '/tools/text-utilities',
                'documentation_url' => null,
                'is_active' => true,
                'is_featured' => false,
                'usage_count' => 18765,
                'created_at' => now()->subMonths(7),
                'updated_at' => now(),
            ],
            [
                'user_id' => $admin->id,
                'name' => 'SQL Formatter',
                'slug' => 'sql-formatter',
                'description' => 'Format and beautify SQL queries with syntax highlighting. Supports MySQL, PostgreSQL, and SQLite dialects.',
                'icon' => 'sql',
                'category' => 'Database',
                'url' => '/tools/sql-formatter',
                'documentation_url' => null,
                'is_active' => true,
                'is_featured' => false,
                'usage_count' => 6543,
                'created_at' => now()->subMonths(3),
                'updated_at' => now(),
            ],
            [
                'user_id' => $admin->id,
                'name' => 'JWT Decoder',
                'slug' => 'jwt-decoder',
                'description' => 'Decode and verify JWT tokens. Inspect header, payload, and signature information.',
                'icon' => 'jwt',
                'category' => 'Security',
                'url' => '/tools/jwt-decoder',
                'documentation_url' => 'https://jwt.io/',
                'is_active' => true,
                'is_featured' => false,
                'usage_count' => 4321,
                'created_at' => now()->subMonths(2),
                'updated_at' => now(),
            ],
            [
                'user_id' => $admin->id,
                'name' => 'Base64 Encoder/Decoder',
                'slug' => 'base64',
                'description' => 'Encode text to Base64 and decode Base64 back to text. Supports both standard and URL-safe Base64.',
                'icon' => 'base64',
                'category' => 'Encoding',
                'url' => '/tools/base64',
                'documentation_url' => null,
                'is_active' => true,
                'is_featured' => false,
                'usage_count' => 9876,
                'created_at' => now()->subMonths(5),
                'updated_at' => now(),
            ],
            [
                'user_id' => $admin->id,
                'name' => 'Timestamp Converter',
                'slug' => 'timestamp-converter',
                'description' => 'Convert Unix timestamps to human-readable dates and vice versa. Supports milliseconds and seconds.',
                'icon' => 'time',
                'category' => 'Developer',
                'url' => '/tools/timestamp-converter',
                'documentation_url' => null,
                'is_active' => true,
                'is_featured' => false,
                'usage_count' => 7654,
                'created_at' => now()->subMonths(4),
                'updated_at' => now(),
            ],
            [
                'user_id' => $admin->id,
                'name' => 'Color Palette Generator',
                'slug' => 'color-palette',
                'description' => 'Generate beautiful color palettes for your designs. Export to CSS, Tailwind, or SCSS variables.',
                'icon' => 'color',
                'category' => 'Design',
                'url' => '/tools/color-palette',
                'documentation_url' => null,
                'is_active' => true,
                'is_featured' => true,
                'usage_count' => 11234,
                'created_at' => now()->subMonths(3),
                'updated_at' => now(),
            ],
        ];

        foreach ($tools as $tool) {
            Tool::create($tool);
        }
    }
}